// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';


export class ElevatorStatus {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ElevatorStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsElevatorStatus(bb:flatbuffers.ByteBuffer, obj?:ElevatorStatus):ElevatorStatus {
  return (obj || new ElevatorStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsElevatorStatus(bb:flatbuffers.ByteBuffer, obj?:ElevatorStatus):ElevatorStatus {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ElevatorStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

floor():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

door():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startElevatorStatus(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addFloor(builder:flatbuffers.Builder, floor:number) {
  builder.addFieldInt8(1, floor, 0);
}

static addDoor(builder:flatbuffers.Builder, door:number) {
  builder.addFieldInt8(2, door, 0);
}

static endElevatorStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createElevatorStatus(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset, floor:number, door:number):flatbuffers.Offset {
  ElevatorStatus.startElevatorStatus(builder);
  ElevatorStatus.add_Metadata(builder, _MetadataOffset);
  ElevatorStatus.addFloor(builder, floor);
  ElevatorStatus.addDoor(builder, door);
  return ElevatorStatus.endElevatorStatus(builder);
}
}
