// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';


export class Pose2Df {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Pose2Df {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPose2Df(bb:flatbuffers.ByteBuffer, obj?:Pose2Df):Pose2Df {
  return (obj || new Pose2Df()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPose2Df(bb:flatbuffers.ByteBuffer, obj?:Pose2Df):Pose2Df {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Pose2Df()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

theta():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startPose2Df(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(2, y, 0.0);
}

static addTheta(builder:flatbuffers.Builder, theta:number) {
  builder.addFieldFloat32(3, theta, 0.0);
}

static endPose2Df(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPose2Df(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset, x:number, y:number, theta:number):flatbuffers.Offset {
  Pose2Df.startPose2Df(builder);
  Pose2Df.add_Metadata(builder, _MetadataOffset);
  Pose2Df.addX(builder, x);
  Pose2Df.addY(builder, y);
  Pose2Df.addTheta(builder, theta);
  return Pose2Df.endPose2Df(builder);
}
}
