### Get server 
GET http://localhost:4000/api/server

### Get devices 
GET http://localhost:4000/api/devices

### Get devices 
GET http://localhost:4000/api/devices?id=1

### Get devices 
GET http://localhost:4000/api/devices?id=1&id=2&id=3

### Get positions 
GET http://localhost:4000/api/positions

### Get position
GET http://localhost:4000/api/positions?deviceId=4

### Get position
GET http://localhost:4000/api/positions?deviceId=1&deviceId=2&deviceId=3

### Add Devices
POST http://localhost:4000/api/devices
Content-Type: application/json

{
    "name": "uav_757",
    "category": "dji_M300",
    "ip": "10.42.0.44",
    "camera":[
        {
            "type": "WebRTC",
            "source": "main"
        }
    ]
}

### Add Devices
POST http://localhost:4000/api/devices
Content-Type: application/json

{
    "name": "uav_758",
    "category": "dji_M300",
    "ip": "10.42.0.44",
    "camera":[]
}

### delete a device

DELETE http://localhost:4000/api/devices/1

### update  a device 
PATCH http://localhost:4000/api/device/2
Content-Type: application/json

{
  "ip": "10.42.0.44"
}

### Devices type
GET http://localhost:4000/api/category

### Atributes 
GET http://localhost:4000/api/category/atributes/dji_M210_noetic

### Atributes
GET http://localhost:4000/api/category/atributesparam/dji_M210_noetic/mode_yaw

### Actions 

GET http://localhost:4000/api/category/actions/dji_M210_noetic


### Commandos 

GET http://localhost:4000/api/commands/send


### Commands types

GET http://localhost:4000/api/commands/types

### send command threat

POST http://localhost:4000/api/commands/send
Content-Type: application/json

{
    "deviceId": 5, 
    "type": "threat"
}

### send command loadmission

POST http://localhost:4000/api/commands/send
Content-Type: application/json

< ./json/loadmission.json

### send command command mission

POST http://localhost:4000/api/commands/send
Content-Type: application/json

{
    "deviceId": 5, 
    "type": "commandMission"
}

### Mission
### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

< ./json/task_Centro1.json

### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

< ./json/gw-sendtasks.json


### setMission
POST http://localhost:4000/api/missions/setMission
Content-Type: application/json

< ./json/mission.json


### varibles 


### varibles 

@uav_id = 4
@mission_id = 1

### get mission
GET  http://localhost:4000/api/missions
### get mission
GET  http://localhost:4000/api/missions?id=72510181

### get mission
GET  http://localhost:4000/api/missions/routes

### get mission route
GET  http://localhost:4000/api/missions/routes?missionId=72510181

### update files

GET  http://localhost:4000/api/missions/updateFiles/{{uav_id}}/{{mission_id}}

### list files
GET  http://localhost:4000/api/missions/listFiles/{{mission_id}}/{{uav_id}}



### show files
GET  http://localhost:4000/api/files/showFiles/{{uav_id}}/{{mission_id}}

### updateFiles
GET  http://localhost:4000/api/files/updateFiles/{{uav_id}}/{{mission_id}}

### download files
### curl http://localhost:4000/api/files/download/mission_1/uav_15/DJI_20231124131954_0001_THRM.jpg --output some.jpg  
GET http://localhost:4000/api/files/download/mission_1243/uav_15/DJI_20231124131954_0001_THRM.jpg
### otro
GET http://localhost:4000/api/files/download/mission_72510181/uav_14/distances.pcd 
### list files GCS
GET http://localhost:4000/api/files/get

### list files GCS
GET http://localhost:4000/api/files/get?missionId=72510181


### list files GCS
GET http://localhost:4000/api/files/get?missionId=57641431  

### list files GCS
GET http://localhost:4000/api/files/listFiles

### Get metadata
POST  http://localhost:4000/api/files/test
Content-Type: application/json

{
    "src":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240226142604_0003_THRM_process.jpg"
}

### list get temp max of metadata
POST  http://localhost:4000/api/files/TempResult
Content-Type: application/json

{
    "src":[
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174110_0013_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174112_0014_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174116_0015_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174122_0016_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240226142604_0003_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174122_0016_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240305104808_0006_THRM_process.jpg"
    ]
}

### list get temp max of metadata
POST  http://localhost:4000/api/files/ProcessImage
Content-Type: application/json

{
    "src":[
      {"dist":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174110_0013_THRM.jpg","ref":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174110_0013_THRM.jpg"},
      {"dist":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174112_0014_THRM.jpg","ref":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174112_0014_THRM.jpg"},
      {"dist":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174116_0015_THRM.jpg","ref":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174116_0015_THRM.jpg"},
      {"dist":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174122_0016_THRM.jpg","ref":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174122_0016_THRM.jpg"},
      {"dist":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240226142604_0003_THRM.jpg","ref":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240226142604_0003_THRM.jpg"},
      {"dist":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174128_0017_THRM.jpg","ref":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174128_0017_THRM.jpg"},
      {"dist":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240305104808_0006_THRM.JPG","ref":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240305104808_0006_THRM.JPG"}
    
    ]
}



### planning
### get planning
GET http://localhost:4000/api/planning/mission

### get planning
GET http://localhost:4000/api/planning/missionstype

### get planning
GET http://localhost:4000/api/planning/missionparam/0

### Ros

POST http://localhost:4000/api/rosConnect

###

GET http://localhost:4000/api/rosConnect

###

GET http://localhost:4000/api/topics


###

GET http://localhost:4000/api/test.png


### Elevation 
GET http://localhost:4000/api/map/elevation?locations=[[44.074221911574284,11.221895356523419]]


### Elevation 
GET https://api.opentopodata.org/v1/eudem25m?locations=37.410266,-6.002490|37.410572,-6.002949|37.411010,-6.003243

### Elevation 
POST http://localhost:4000/api/map/elevation
Content-Type: application/json

< ./json/elevationRoute.json

### Images
GET http://localhost:4000/api/placeholder


### Images
GET http://localhost:4000/api/placeholder


### Image ros
GET http://localhost:4000/api/media/:deviceid

### Image Ros
GET http://localhost:4000/api/media1/:deviceid

### datetime
GET http://localhost:4000/api/server/datetime


### server config
GET http://localhost:4000/api/server


### Test external application request  Token
GET http://localhost:4000/api/ExtApp/updateToken

### Test external application request start
POST  http://localhost:4000/api/ExtApp/start
Content-Type: application/json

< ./json/missionresponse.json

### Test external application request result
POST  http://localhost:4000/api/ExtApp/result
Content-Type: application/json

{
  "mission_id": 1234231,
  "resolution_code": 0
}

### Test external application request media
POST  http://localhost:4000/api/ExtApp/media
Content-Type: application/json

{
  "mission_id": 1234231,
  "results": {
    "data": [
              {
                "latitude": 37.09241,
                "longitude": -5.232,
                "measures": [
                  {
                    "name": "minDistance",
                    "value": 25.34
                  }
                ]
              }
            ],
  "files": [
      "mission_1243/uav_15/DJI_20231124131954_0001_THRM.jpg",
      "mission_1243/uav_15/captura.jpg"
      ]
      }
}

###
POST http://192.168.1.180:8004/input_test
Content-Type: application/json

{
    "deviceId": 5, 
    "type": "threat"
}

###
GET http://192.168.1.180:8004/get_plan?IDs=1234

###
GET  http://localhost:4000/api/missions/test
###
GET http://127.0.0.1:8004/get_plan?IDs=76327900

### 
POST http://127.0.0.1:8004/mission_request
Content-Type: application/json

{
  "id": "76327903",
  "locations": [
    {
      "name": "Elements",
      "items": [
        {"latitude": 37.19384681403371, "longitude": -6.702598762315071},
        {"latitude": 37.19280537019709, "longitude": -6.701476542699256}
      ]
    }
  ],
  "case": 0,
  "meteo": [],
  "devices": [
    {
      "settings": {
        "base": [37.1340964847625, -6.472237657544976, "base"],
        "inspection_speed": 7,
        "navigation_speed": 15,
        "vertical_offset": 10,
        "horizontal_offset": 10,
        "tower_height": 10,
        "security_height": 10,
        "landing_mode": 2
      },
      "id": "uav_3",
      "category": "px4"
    },
    {
      "settings": {
        "base": [37.1340964847625, -6.472237657544976, "base"],
        "inspection_speed": 7,
        "navigation_speed": 15,
        "vertical_offset": 10,
        "horizontal_offset": 10,
        "tower_height": 10,
        "security_height": 10,
        "landing_mode": 2
      },
      "id": "uav_1",
      "category": "dji_M210_melodic"
    },
    {
      "settings": {
        "base": [37.1340964847625, -6.472237657544976, "base"],
        "inspection_speed": 7,
        "navigation_speed": 15,
        "vertical_offset": 10,
        "horizontal_offset": 10,
        "tower_height": 10,
        "security_height": 10,
        "landing_mode": 2
      },
      "id": "uav_14",
      "category": "dji_M300"
    }
  ]
}
###
POST http://127.0.0.1:8004/mission_request
Content-Type: application/json

{
  "id": "76327900",
  "case": 0,
  "meteo": [],
  "locations": [
    {
      "name": "Elements",
      "items": [
        {"latitude": 37.19384681403371, "longitude": -6.702598762315071},
        {"latitude": 37.19280537019709, "longitude": -6.701476542699256}
      ]
    }
  ],
  "devices": [
    {
      "settings": {
        "base": [37.19384768456065, -6.7029665624597465, "base"],
        "inspection_speed": 7,
        "navigation_speed": 15,
        "vertical_offset": 10,
        "horizontal_offset": 10,
        "tower_height": 10,
        "security_height": 10,
        "landing_mode": 2
      },
      "id": "uav_3",
      "category": "px4"
    },
    {
      "settings": {
        "base": [37.04392450222122, -6.568677029462045, "base"],
        "inspection_speed": 7,
        "navigation_speed": 15,
        "vertical_offset": 10,
        "horizontal_offset": 10,
        "tower_height": 10,
        "security_height": 10,
        "landing_mode": 2
      },
      "id": "uav_1",
      "category": "dji_M210_melodic"
    },
    {
      "settings": {
        "base": [37.1340964847625, -6.472237657544976, "base"],
        "inspection_speed": 7,
        "navigation_speed": 15,
        "vertical_offset": 10,
        "horizontal_offset": 10,
        "tower_height": 10,
        "security_height": 10,
        "landing_mode": 2
      },
      "id": "uav_14",
      "category": "dji_M300"
    }
  ]
}

