### Get devices 
GET http://localhost:4000/api/devices

### Get positions 
GET http://localhost:4000/api/positions

### Get position
GET http://localhost:4000/api/positions?id=1

### Add Devices
POST http://localhost:4000/api/devices
Content-Type: application/json

{
    "name": "uav_757",
    "category": "dji_M300",
    "ip": "10.42.0.44",
    "camera":[
        {
            "type": "WebRTC",
            "source": "main"
        }
    ]
}

### Add Devices
POST http://localhost:4000/api/devices
Content-Type: application/json

{
    "name": "uav_758",
    "category": "dji_M300",
    "ip": "10.42.0.44",
    "camera":[]
}

### delete a device

DELETE http://localhost:4000/api/devices/7

### update  a device 
PATCH http://localhost:4000/api/device/2
Content-Type: application/json

{
  "ip": "10.42.0.44"
}

### Devices type
GET http://localhost:4000/api/category

### Atributes 
GET http://localhost:4000/api/category/atributes/dji_M210_noetic

### Atributes
GET http://localhost:4000/api/category/atributesparam/dji_M210_noetic/mode_yaw

### Actions 

GET http://localhost:4000/api/category/actions/dji_M210_noetic

### Sendtask
POST http://localhost:4000/api/commands/sendTask
Content-Type: application/json

< ./json/task.json

### Commandos 

GET http://localhost:4000/api/commands/send


### Commands types

GET http://localhost:4000/api/commands/types

### send command threat

POST http://localhost:4000/api/commands/send
Content-Type: application/json

{
    "deviceId": 7, 
    "type": "threat"
}

### send command loadmission

POST http://localhost:4000/api/commands/send
Content-Type: application/json

< ./json/loadmission.json

### send command command mission

POST http://localhost:4000/api/commands/send
Content-Type: application/json

{
    "deviceId": 7, 
    "type": "commandMission"
}

### Mission

### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

< ./json/task.json

# varibles 

@uav_id = 4
@mission_id = 1
### get mission

### show files
GET  http://localhost:4000/api/missions/showFiles/{{uav_id}}/{{mission_id}}

### update files

GET  http://localhost:4000/api/missions/updateFiles/{{uav_id}}/{{mission_id}}

### list files
GET  http://localhost:4000/api/missions/listFiles/{{mission_id}}/{{uav_id}}

### Ros

POST http://localhost:4000/api/rosConnect

###

GET http://localhost:4000/api/rosConnect

###

GET http://localhost:4000/api/topics


###

GET http://localhost:4000/api/test.png


### Elevation 

GET http://localhost:4000/api/map/elevation


### Elevation 

POST http://localhost:4000/api/map/elevation
Content-Type: application/json

{
  "routes":[
      [
      [37.410266, -6.002490,2],
      [37.410572, -6.002949,3],
      [37.411010, -6.003243,3]
      ],
      [
      [37.410446, -6.002205,12],
      [37.410241, -6.002221,12],
      [37.410302, -6.002534,12]
      ]
    ]
}

### Images
GET http://localhost:4000/api/placeholder


### Images
GET http://localhost:4000/api/placeholder


### Image ros
GET http://localhost:4000/api/media/:deviceid

### Image Ros
GET http://localhost:4000/api/media1/:deviceid

### datetime
GET http://localhost:4000/api/utils/datetime

