###
GET http://localhost:1234/test

###
# @name login
POST http://localhost:1234/token/provide/RESISTO-API
Content-Type: application/x-www-form-urlencoded

username="drone"
&password="F1PpE9V!E#Pwz8k53b7b"


### Mission Result 2
POST http://localhost:1234/resultado_mision
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "mission_id": 1234,
  "resolution_code": 0,
  "resultados": [
  "mission_1/uav_1/DJI_20231124131954_0001_WIDE.jpg",
  "mission_1/uav_1/DJI_20231124131954_0001_ZOOM.jpg",
  "mission_1/uav_1/DJI_20231124131954_0001_THRM.jpg"
  ]
}

