// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';


export class ElevatorCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ElevatorCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsElevatorCommand(bb:flatbuffers.ByteBuffer, obj?:ElevatorCommand):ElevatorCommand {
  return (obj || new ElevatorCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsElevatorCommand(bb:flatbuffers.ByteBuffer, obj?:ElevatorCommand):ElevatorCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ElevatorCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

floorCmd():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

holdDoor():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startElevatorCommand(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addFloorCmd(builder:flatbuffers.Builder, floorCmd:number) {
  builder.addFieldInt8(1, floorCmd, 0);
}

static addHoldDoor(builder:flatbuffers.Builder, holdDoor:boolean) {
  builder.addFieldInt8(2, +holdDoor, +false);
}

static endElevatorCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createElevatorCommand(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset, floorCmd:number, holdDoor:boolean):flatbuffers.Offset {
  ElevatorCommand.startElevatorCommand(builder);
  ElevatorCommand.add_Metadata(builder, _MetadataOffset);
  ElevatorCommand.addFloorCmd(builder, floorCmd);
  ElevatorCommand.addHoldDoor(builder, holdDoor);
  return ElevatorCommand.endElevatorCommand(builder);
}
}
