name: muav-gui
root: ~/
on_project_exit: tmux kill-window

windows:
  - GCS:
      layout: main-vertical
      panes:
        - backend:
            - cd ~/work/px4/multiuav_gui/server
            - nvm use 20
            - sleep 3
            - npm run server
        - frontend:
            - cd ~/work/px4/multiuav_gui/client
            - nvm use 20
            - open -a "Google Chrome" http://127.0.0.1:3000
            - sleep 2;npm run start
  - Docker:
      layout: tiled
      panes:
        - multimaster:
            - cd ~/work/px4/multiuav_gui/docker
            - ./container_run.sh
            - cd /home/user
            - roslaunch aerialcore_gui connect_uas.launch
        - bag:
            - cd ~/work/px4/multiuav_gui/docker
            - ./container_run.sh
            - cd /home/user/bags
            - sleep 10;
            - rosbag play -l uav_2_2023_10_26_10_02.bag
        - bag1:
            - cd ~/work/px4/multiuav_gui/docker
            - ./container_run.sh
            - cd /home/user/bags/uav_14
            - sleep 10;
            - rosbag play -l uav_15_2023_12_12_16_24.bag
        - aux:
            - cd ~/work/px4/multiuav_gui/docker
            - ./container_run.sh
            - cd /home/user/catkin_ws
