init:
  - name: 'uav_1'
    category: 'dji_M210_melodic_rtk'
    ip: '10.42.0.99'
    user: 'grvc'
    camera:
      - type: 'WebRTC'
        source: 'main'

  - name: 'uav_2'
    category: 'dji_M210_noetic_rtk'
    ip: '10.42.0.43'
    camera:
      - type: 'WebRTC'
        source: 'main'
