// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';


export class WaypointV2MissionStatePush {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WaypointV2MissionStatePush {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWaypointV2MissionStatePush(bb:flatbuffers.ByteBuffer, obj?:WaypointV2MissionStatePush):WaypointV2MissionStatePush {
  return (obj || new WaypointV2MissionStatePush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWaypointV2MissionStatePush(bb:flatbuffers.ByteBuffer, obj?:WaypointV2MissionStatePush):WaypointV2MissionStatePush {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WaypointV2MissionStatePush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

commonDataVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

commonDataLen():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

curWaypointIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

state():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

velocity():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startWaypointV2MissionStatePush(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addCommonDataVersion(builder:flatbuffers.Builder, commonDataVersion:number) {
  builder.addFieldInt8(1, commonDataVersion, 0);
}

static addCommonDataLen(builder:flatbuffers.Builder, commonDataLen:number) {
  builder.addFieldInt16(2, commonDataLen, 0);
}

static addCurWaypointIndex(builder:flatbuffers.Builder, curWaypointIndex:number) {
  builder.addFieldInt16(3, curWaypointIndex, 0);
}

static addState(builder:flatbuffers.Builder, state:number) {
  builder.addFieldInt8(4, state, 0);
}

static addVelocity(builder:flatbuffers.Builder, velocity:number) {
  builder.addFieldInt16(5, velocity, 0);
}

static endWaypointV2MissionStatePush(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWaypointV2MissionStatePush(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset, commonDataVersion:number, commonDataLen:number, curWaypointIndex:number, state:number, velocity:number):flatbuffers.Offset {
  WaypointV2MissionStatePush.startWaypointV2MissionStatePush(builder);
  WaypointV2MissionStatePush.add_Metadata(builder, _MetadataOffset);
  WaypointV2MissionStatePush.addCommonDataVersion(builder, commonDataVersion);
  WaypointV2MissionStatePush.addCommonDataLen(builder, commonDataLen);
  WaypointV2MissionStatePush.addCurWaypointIndex(builder, curWaypointIndex);
  WaypointV2MissionStatePush.addState(builder, state);
  WaypointV2MissionStatePush.addVelocity(builder, velocity);
  return WaypointV2MissionStatePush.endWaypointV2MissionStatePush(builder);
}
}
