### Get server 
GET http://localhost:4000/api/server

### Get devices 
GET http://localhost:4000/api/devices

### Get devices 
GET http://localhost:4000/api/devices/1

### Get devices 
GET http://localhost:4000/api/devices?id=1

### Get devices 
GET http://localhost:4000/api/devices?id=1&id=2&id=3

### Get positions 
GET http://localhost:4000/api/positions

### Get position
GET http://localhost:4000/api/positions?deviceId=4

### Get position
GET http://localhost:4000/api/positions?deviceId=1&deviceId=2&deviceId=3

### Add Devices
POST http://localhost:4000/api/devices
Content-Type: application/json

{
    "name": "uav_14",
    "category": "dji_M300",
    "protocol": "ros",  
    "ip": "10.42.0.44",
    "camera":[
        {
            "type": "WebRTC",
            "source": "main"
        }
    ],
    "files":[
        {
            "type": "onboard_computer",
            "url": "sftp://one:1234@127.0.0.1:4021"
        }
    ]
}

### Add Devices
POST http://localhost:4000/api/devices
Content-Type: application/json

{
    "name": "uav_758",
    "category": "dji_M300",
    "ip": "10.42.0.44",
    "camera":[]
}

### delete a device

DELETE http://localhost:4000/api/devices/1

### update  a device 
PATCH http://localhost:4000/api/device/2
Content-Type: application/json

{
  "ip": "10.42.0.44"
}

### Get list of category
GET http://localhost:4000/api/category


### Get category info
GET http://localhost:4000/api/category/dji_M300

### Get message info
GET http://localhost:4000/api/category/messages/

### Atributes 
GET http://localhost:4000/api/category/atributes/dji_M210_noetic

### Atributes
GET http://localhost:4000/api/category/atributesparam/dji_M210_noetic/mode_yaw

### Actions 

GET http://localhost:4000/api/category/actions/dji_M210_noetic


### Commandos 

GET http://localhost:4000/api/commands/send


### Commands types

GET http://localhost:4000/api/commands/types

### send command threat

POST http://localhost:4000/api/commands/send
Content-Type: application/json

{
    "deviceId": 5, 
    "type": "threat"
}

### send command loadmission

POST http://localhost:4000/api/commands/send
Content-Type: application/json

< ./json/loadmission.json

### send command command mission

POST http://localhost:4000/api/commands/send
Content-Type: application/json

{
    "deviceId": 5, 
    "type": "commandMission"
}

### Mission
### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

< ./json/task_Centro2.json

### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

< ./json/gw-sendtasks.json


### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

< ./json/gw-sendtasks2.json





### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

{
  "id": 118,
  "name": "Prueba tramo largo drone",
  "objetivo": 0,
  "loc":[
    {
      "name": "Centro1",
      "geo_points": [
        {
          "lon": 37.0706021117295,
          "lat": -6.6254878174821
        },
        {
          "lon": 37.1060530670846,
          "lat": -6.69479130605354
        }
      ]
    }
  ],
  "meteo": [                                                                                                                                                                               
    {                                                                                                                                                                                    
      "lat": 37.164528,                                                                                                                                                                    
      "lon": -5.611474,                                                                                                                                                                    
      "wind_vel": 21.24,                                                                                                                                                                   
      "wind_dir": 92,                                                                                                                                                                      
      "temp": 13.4,                                                                                                                                                                        
      "humidity": 13.4,                                                                                                                                                                    
      "pressure": 0                                                                                                                                                                        
    }                                                                                                                                                                                    
  ]      
}

### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

{
  "id": 119,
  "name": "Prueba tramo largo drone",
  "objetivo": 0,
  "loc":[
    {
      "name": "Centro1",
      "geo_points": [
        {
          "lat": 37.0706021117295,
          "lon": -6.6254878174821
        },
        {
          "lat": 37.1060530670846,
          "lon": -6.69479130605354
        }
      ]
    }
  ],
  "meteo": [                                                                                                                                                                               
    {                                                                                                                                                                                    
      "lat": 37.164528,                                                                                                                                                                    
      "lon": -5.611474,                                                                                                                                                                    
      "wind_vel": 21.24,                                                                                                                                                                   
      "wind_dir": 92,                                                                                                                                                                      
      "temp": 13.4,                                                                                                                                                                        
      "humidity": 13.4,                                                                                                                                                                    
      "pressure": 0                                                                                                                                                                        
    }                                                                                                                                                                                    
  ]      
}
### Sendtask
POST http://localhost:4000/api/missions/sendTask
Content-Type: application/json

{
  "objetivo": 3,
  "loc": [
    {
      "name": "alarma_meteo_apoyo",
      "geo_points": [
        {
          "lat": 37.136565344467,
          "lon": -6.47123160018281
        }
      ]
    }
  ],
  "meteo": [
    {
      "lat": 37.136565344467,
      "lon": -6.47123160018281
    }
  ],
  "mission_id":104
}
### setMission
POST http://localhost:4000/api/missions/setMission
Content-Type: application/json

< ./json/mission.json


### varibles 

@uav_id = 3
@mission_id = 1

### get mission
GET  http://localhost:4000/api/missions
### get mission
GET  http://localhost:4000/api/missions?id=72510181

### get mission
GET  http://localhost:4000/api/missions/routes

### get mission route
GET  http://localhost:4000/api/missions/routes?missionId=72510181

### update files

GET  http://localhost:4000/api/missions/updateFiles/{{uav_id}}/{{mission_id}}

### list files
GET  http://localhost:4000/api/missions/listFiles/{{mission_id}}/{{uav_id}}



### show files
GET  http://localhost:4000/api/files/showFiles/{{uav_id}}/{{mission_id}}

### updateFiles
GET  http://localhost:4000/api/files/updateFiles/{{uav_id}}/{{mission_id}}

### download files
### curl http://localhost:4000/api/files/download/mission_1/uav_15/DJI_20231124131954_0001_THRM.jpg --output some.jpg  
GET http://localhost:4000/api/files/download/mission_1243/uav_15/DJI_20231124131954_0001_THRM.jpg
### otro
GET http://localhost:4000/api/files/download/mission_72510181/uav_14/distances.pcd 
### list files GCS
GET http://localhost:4000/api/files/get

### list files GCS
GET http://localhost:4000/api/files/get?missionId=72510181


### list files GCS
GET http://localhost:4000/api/files/get?missionId=57641431  

### list files GCS
GET http://localhost:4000/api/files/listFiles

### Get metadata
POST  http://localhost:4000/api/files/test
Content-Type: application/json

{
    "src":"/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240226142604_0003_THRM_process.jpg"
}

### list get temp max of metadata
POST  http://localhost:4000/api/files/TempResult
Content-Type: application/json

{
    "src":[
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174110_0013_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174112_0014_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174116_0015_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174122_0016_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240226142604_0003_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240223174122_0016_THRM_process.jpg",
      "/home/grvc/work/GCS_media/mission_92254290/uav_14/DJI_20240305104808_0006_THRM_process.jpg"
    ]
}

### list get temp max of metadata
POST  http://localhost:4000/api/files/ProcessImage
Content-Type: application/json

{
    "src":[
      "/home/grvc/work/px4/uav_media/test/10-08-14-488-radiometric.jpg",
      "/home/grvc/work/px4/uav_media/test/10-08-14-488-radiometric.tiff",
      "/home/grvc/work/px4/uav_media/test/DJI_20240305122546_0001_THRM.jpg"
    ]
}



### planning
### get planning
GET http://localhost:4000/api/planning/mission

### get planning
GET http://localhost:4000/api/planning/missionstype

### get planning
GET http://localhost:4000/api/planning/missionparam/0

### get markersType
GET http://localhost:4000/api/planning/getMarkersTypes
### get Markers
GET http://localhost:4000/api/planning/getMarkers
  
### get bases
GET http://localhost:4000/api/planning/getBases

### --------- ROS -------------
### get topics
GET http://localhost:4000/api/ros/topics

### get services
GET http://localhost:4000/api/ros/services

### get service type
GET http://localhost:4000/api/ros/service_type?service=/px4_3/land

### get service type
GET http://localhost:4000/api/ros/service_type?service=/px4_3/offboard/mission_load

### check service request structure
GET http://localhost:4000/api/ros/service_request_details?type=std_srvs/srv/Trigger


### check service request structure
GET http://localhost:4000/api/ros/service_request_details?type=muav_gcs_interfaces/srv/LoadMission


### call service 
POST http://localhost:4000/api/ros/service_call
Content-Type: application/json

{
  "service": "/px4_3/land",
  "messageType": "std_srvs/srv/Trigger",
  "message": {}
}

### call service 
POST http://localhost:4000/api/ros/service_call
Content-Type: application/json

{
  "service": "/px4_3/takeoff",
  "messageType": "px4_msgs/srv/VehicleCommand",
  "message": {
    "request": {
      "timestamp":0,
      "param1":1 ,
      "param2":2,
      "param3":3,
      "param4":4,
      "param5":5,
      "param6":6,
      "param7":7,
      "source_system":1,
      "source_component":1,
      "target_system":1,
      "target_component":1,
      "command": 22,
      "confirmation":0,
      "from_external":true
     }
   }
}


### get topic type
GET http://localhost:4000/api/ros/topics_type?topic=/px4_3/fmu/out/vehicle_local_position

### get message details
GET http://localhost:4000/api/ros/message_details?type=px4_msgs/msg/VehicleLocalPosition

### get message details turtlesim
GET http://localhost:4000/api/ros/message_details?type=geometry_msgs/msg/Twist


### get message details turtlesim
GET http://localhost:4000/api/ros/message_details?type=geometry_msgs/msg/Twist1
### get publisher
GET http://localhost:4000/api/ros/publisher?topic=/px4_3/fmu/out/vehicle_local_position


### get message
GET http://localhost:4000/api/ros/subscribe_once?topic=/px4_3/fmu/out/vehicle_local_position

### get message
GET http://localhost:4000/api/ros/subscribe_once?topic=/bcr_bot/odom

### get message turtlebot
GET http://localhost:4000/api/ros/subscribe_once?topic=/turtle1/pose

### get action servers

GET http://localhost:4000/api/ros/action_servers 


### send action goal navigate_to_pose
POST http://localhost:4000/api/ros/action_send_goal
Content-Type: application/json

{
  "action": "navigate_to_pose",
  "actionType": "nav2_msgs/action/NavigateToPose",
  "message": {
    "pose": {
      "header": {
        "frame_id": "map"
      },
      "pose": {
        "position": {
          "x": 16.0,
          "y": -24.0,
          "z": 0.0
        },
        "orientation": {
          "x": 0.0,   
          "y": 0.0,
          "z": 0.7071,
          "w": 0.7071
        }
      }
    },
    "behavior_tree": ""
  }
}
### send stop action navigate_to_pose
POST http://localhost:4000/api/ros/action_cancel_goal
Content-Type: application/json
{
  "action": "navigate_to_pose"
}

### pub topic
POST http://localhost:4000/api/ros/publish
Content-Type: application/json

{
  "topic": "px4_3/fmu/in/trajectory_setpoint",
  "messageType": "px4_msgs/msg/TrajectorySetpoint",
  "message": {
    "timestamp": 1755871255821361,
    "position": [
      0.0,
      0.0,
      -10.0
    ],
    "velocity": [
      0.0,
      0.0,
      0.0
    ],
    "acceleration": [
      0.0,
      0.0,
      0.0
    ],
    "jerk": [
      0.0,
      0.0,
      0.0
    ],
    "yaw": 1.5707900524139404,
    "yawspeed": 1.0
  }
}

### pub  goto
POST http://localhost:4000/api/ros/publish
Content-Type: application/json

{
  "topic": "/px4_3/fmu/in/goto_setpoint",
  "messageType": "px4_msgs/msg/GotoSetpoint",
  "message": {
    "timestamp": 0,
    "position": [
      10,
      10,
      10
    ],
    "flag_control_heading": false,
    "heading": 0,
    "flag_set_max_horizontal_speed": false,
    "max_horizontal_speed": 0,
    "flag_set_max_vertical_speed": false,
    "max_vertical_speed": 0,
    "flag_set_max_heading_rate": false,
    "max_heading_rate": 0
  }
}
### pub a nav2 move 
POST http://localhost:4000/api/ros/publish
Content-Type: application/json

{
  "topic": "/bcr_bot/goal_pose_cmd",
  "messageType": "geometry_msgs/msg/PoseStamped",
  "message": {
    "header": {
      "stamp": {
        "sec": 0,
        "nanosec": 0
      },
      "frame_id": "map"
    },
    "pose": {
      "position": {
        "x": 20.0,
        "y": -35.0,
        "z": 0.0
      },
      "orientation": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.7071068,
        "w": 0.7071068
      }
    }
  }
}
### pub a nav2 move 
POST http://localhost:4000/api/ros/publish
Content-Type: application/json

{
  "topic": "/goal_pose",
  "messageType": "geometry_msgs/msg/PoseStamped",
  "message": {
    "header": {
      "stamp": {
        "sec": 0,
        "nanosec": 0
      },
      "frame_id": "map"
    },
    "pose": {
      "position": {
        "x": -30.0,
        "y": -30.0,
        "z": 0.0
      },
      "orientation": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.7071068,
        "w": 0.7071068
      }
    }
  }
}



### pub topic
POST http://localhost:4000/api/ros/publish
Content-Type: application/json

{
  "topic": "/turtle1/cmd_vel",
  "messageType": "geometry_msgs/msg/Twist",
  "message": {
    "linear": {
      "x": 1.0,
      "y": 0.0,
      "z": 0.0
    },
    "angular": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    }
  }
}

### test images
GET http://localhost:4000/api/test.png


### test images 
GET http://localhost:4000/api/test.png


### Elevation 
GET http://localhost:4000/api/map/elevation?locations=[[44.074221911574284,11.221895356523419]]


### Elevation 
GET https://api.opentopodata.org/v1/eudem25m?locations=37.410266,-6.002490|37.410572,-6.002949|37.411010,-6.003243

### Elevation 
POST http://localhost:4000/api/map/elevation
Content-Type: application/json

< ./json/elevationRoute.json

### Images
GET http://localhost:4000/api/placeholder


### Images
GET http://localhost:4000/api/placeholder


### Image ros
GET http://localhost:4000/api/media/:deviceid

### Image Ros
GET http://localhost:4000/api/media1/:deviceid

### datetime
GET http://localhost:4000/api/server/datetime


### server config
GET http://localhost:4000/api/server


### Test external application request  Token
GET http://localhost:4000/api/ExtApp/updateToken

### Test external application request start
POST  http://localhost:4000/api/ExtApp/start
Content-Type: application/json

< ./json/missionresponse.json

### Test external application request result
POST  http://localhost:4000/api/ExtApp/result
Content-Type: application/json

{
  "mission_id": 1234231,
  "resolution_code": 0
}

### Test external application request media
POST  http://localhost:4000/api/ExtApp/media
Content-Type: application/json

{
  "mission_id": 1234231,
  "results": {
    "data": [
              {
                "latitude": 37.09241,
                "longitude": -5.232,
                "measures": [
                  {
                    "name": "minDistance",
                    "value": 25.34
                  }
                ]
              }
            ],
  "files": [
      "mission_1243/uav_15/DJI_20231124131954_0001_THRM.jpg",
      "mission_1243/uav_15/captura.jpg"
      ]
      }
}

### 
GET http://localhost:4000/api/events HTTP/1.1

###
POST http://192.168.1.180:8004/input_test
Content-Type: application/json

{
    "deviceId": 5, 
    "type": "threat"
}

###
GET http://192.168.1.180:8004/get_plan?IDs=1234

###
GET  http://localhost:4000/api/missions/test
###
GET http://127.0.0.1:8004/get_plan?IDs=76327900

### 
POST http://127.0.0.1:8004/mission_request
Content-Type: application/json

< ./json/missionRequest1.json

###
POST http://127.0.0.1:8004/mission_request
Content-Type: application/json

< ./json/missionRequest2.json

###
POST http://localhost:4000/api/chat
Content-Type: application/json

{
  "provider": "gemini",
  "message":"cual es la capital de españa?"
}

### ============================================                                                                                                                                                      
### Chat API Tests - server/routes/chat.js                                                                                                                                                            
### ============================================                                                                                                                                                      
### Base URL: http://localhost:4000/api/chat                                                                                                                                                          
                                                                                                                                                                                                      
### --------------------------------------------                                                                                                                                                      
### POST / - Enviar mensaje al LLM                                                                                                                                                                    
### --------------------------------------------                                                                                                                                                      
                                                                                                                                                                                                      
### Enviar mensaje simple                                                                                                                                                                             
POST http://localhost:4000/api/chat                                                                                                                                                                   
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
  "message": "Hola, ¿cuántos drones hay conectados?"                                                                                                                                                  
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### Enviar mensaje con chatId específico                                                                                                                                                              
POST http://localhost:4000/api/chat                                                                                                                                                                   
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
  "message": "Dame el estado de todos los dispositivos",                                                                                                                                              
  "chatId": "mission-planning-001"                                                                                                                                                                    
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### Error: mensaje vacío (espera 400)                                                                                                                                                                 
POST http://localhost:4000/api/chat                                                                                                                                                                   
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
  "message": ""                                                                                                                                                                                       
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### Error: sin campo message (espera 400)                                                                                                                                                             
POST http://localhost:4000/api/chat                                                                                                                                                                   
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
  "chatId": "test-chat"                                                                                                                                                                               
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### --------------------------------------------                                                                                                                                                      
### GET /chats - Listar todos los chats                                                                                                                                                               
### --------------------------------------------                                                                                                                                                      
                                                                                                                                                                                                      
### Obtener lista de chats                                                                                                                                                                            
GET http://localhost:4000/api/chat/chats                                                                                                                                                              
                                                                                                                                                                                                      
### --------------------------------------------                                                                                                                                                      
### GET /history/:chatId - Obtener historial                                                                                                                                                          
### --------------------------------------------                                                                                                                                                      
                                                                                                                                                                                                      
### Obtener historial de un chat específico                                                                                                                                                           
GET http://localhost:4000/api/chat/history/default_http                                                                                                                                               
                                                                                                                                                                                                      
### Obtener historial de chat personalizado                                                                                                                                                           
GET http://localhost:4000/api/chat/history/mission-planning-001                                                                                                                                       
                                                                                                                                                                                                      
### Chat que no existe (debería devolver array vacío o error)                                                                                                                                         
GET http://localhost:4000/api/chat/history/chat-inexistente-xyz                                                                                                                                       
                                                                                                                                                                                                      
### --------------------------------------------                                                                                                                                                      
### PATCH /chats/:chatId - Renombrar chat                                                                                                                                                             
### --------------------------------------------                                                                                                                                                      
                                                                                                                                                                                                      
### Renombrar un chat                                                                                                                                                                                 
PATCH http://localhost:4000/api/chat/chats/default_http                                                                                                                                               
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
  "name": "Chat Principal"                                                                                                                                                                            
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### Renombrar chat personalizado                                                                                                                                                                      
PATCH http://localhost:4000/api/chat/chats/mission-planning-001                                                                                                                                       
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
  "name": "Planificación Misión Norte"                                                                                                                                                                
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### Error: sin nombre (espera 400)                                                                                                                                                                    
PATCH http://localhost:4000/api/chat/chats/default_http                                                                                                                                               
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### Error: nombre vacío (espera 400)                                                                                                                                                                  
PATCH http://localhost:4000/api/chat/chats/default_http                                                                                                                                               
Content-Type: application/json                                                                                                                                                                        
                                                                                                                                                                                                      
{                                                                                                                                                                                                     
  "name": ""                                                                                                                                                                                          
}                                                                                                                                                                                                     
                                                                                                                                                                                                      
### --------------------------------------------                                                                                                                                                      
### DELETE /chats/:chatId - Eliminar chat                                                                                                                                                             
### --------------------------------------------                                                                                                                                                      
                                                                                                                                                                                                      
### Soft delete (marca como eliminado, mantiene en DB)                                                                                                                                                
DELETE http://localhost:4000/api/chat/chats/chat-temporal                                                                                                                                             
                                                                                                                                                                                                      
### Hard delete (elimina permanentemente de DB)                                                                                                                                                       
DELETE http://localhost:4000/api/chat/chats/chat-temporal?hard=true                                 

### second planning chat
POST  http://localhost:4000/api/chat/build_mission_plan_xyz
content-type: application/json

{
  "chat_id": "chat_1768998561052_r0rmi3e",
  "target_elements": [
    {
      "name": "A1",
      "type": "windTurbine",
      "group_name": "Line A",
      "position": {
        "lat": 41.68559036996601,
        "lng": -8.857866056140523,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "A2",
      "type": "windTurbine",
      "group_name": "Line A",
      "position": {
        "lat": 41.68635449398681,
        "lng": -8.857866056140523,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "A3",
      "type": "windTurbine",
      "group_name": "Line A",
      "position": {
        "lat": 41.68718563612592,
        "lng": -8.857919908575411,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "A4",
      "type": "windTurbine",
      "group_name": "Line A",
      "position": {
        "lat": 41.68719904155651,
        "lng": -8.856645400947343,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "A5",
      "type": "windTurbine",
      "group_name": "Line A",
      "position": {
        "lat": 41.68635449398681,
        "lng": -8.856681302571161,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "A6",
      "type": "windTurbine",
      "group_name": "Line A",
      "position": {
        "lat": 41.68557696420092,
        "lng": -8.856663351759266,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "B1",
      "type": "windTurbine",
      "group_name": "Line B",
      "position": {
        "lat": 41.685657398752284,
        "lng": -8.859373924319044,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "B2",
      "type": "windTurbine",
      "group_name": "Line B",
      "position": {
        "lat": 41.68644833315312,
        "lng": -8.859373924319044,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "B3",
      "type": "windTurbine",
      "group_name": "Line B",
      "position": {
        "lat": 41.68721244698364,
        "lng": -8.859391875130939,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "B4",
      "type": "windTurbine",
      "group_name": "Line B",
      "position": {
        "lat": 41.68801676752793,
        "lng": -8.859391875130939,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "B5",
      "type": "windTurbine",
      "group_name": "Line B",
      "position": {
        "lat": 41.68801676752793,
        "lng": -8.857937859386396,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    },
    {
      "name": "B6",
      "type": "windTurbine",
      "group_name": "Line B",
      "position": {
        "lat": 41.68800336226772,
        "lng": -8.856699253382175,
        "alt": 0
      },
      "characteristics": "offshore wind turbine, hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, min_tip_height:52m, max_tip_height:108m, yaw_orientation:90deg (East), blades: stopped",
      "metadata": "Sea level 0m AGL"
    }
  ],
  "group_information": [
    {
      "elements_name": "Line A, Line B",
      "group_name": "offshore wind turbines",
      "shared_characteristics": "All turbines offshore at Viana do Castelo, Portugal. Sea level 0m AGL. hub_height:80m, rotor_diameter:56m, blade_length:28m, blade_count:3, tower_diameter:6m, yaw_orientation:90deg (facing East). blades currently stopped."
    }
  ],
  "points_of_interest": [],
  "drone_information": [
    {
      "name": "px4_3",
      "type": "px4_ros2",
      "location": {
        "lat": 41.687343853854834,
        "lng": -8.847763540168517,
        "alt": 100.3
      }
    },
    {
      "name": "px4_2",
      "type": "px4_ros2",
      "location": {
        "lat": 41.68710085298747,
        "lng": -8.847727001560585,
        "alt": 100.4
      }
    }
  ],
  "mission_requirements": {
    "mission_type": "fast",
    "mission_details": "Inspección simple de 12 aerogeneradores offshore (Líneas A y B) en Viana do Castelo. 1 waypoint frontal por turbina, a 84 m de distancia (1.5x rotor_diameter/2) con altura 80 m AGL (mitad vertical entre 52 m y 108 m). Yaw -90° (o 270°) apuntando al centro desde el frente (turbinas orientadas a 90°). Orden de visita optimizado por vecino más cercano desde la posición actual del dron. Altitud máxima <120 m. Velocidad 5 m/s."
  },
  "user_context": {
    "user_request": "crea una mission rapida para la inspecion de los aerogeneadores que se encuentran offshore en viana de castelo",
    "additional_info": {
      "priority": "high",
      "language": "es",
      "constraints": [],
      "notes": "Reconocimiento rápido solicitado. Sin requisitos especiales adicionales."
    }
  }
}

### verification
POST  http://localhost:4000/api/chat/validate_mission_briefing
content-type: application/json

{
  "origin_global": {
    "lat": 41.68722237457937,
    "lng": -8.847745085750113,
    "alt": 0
  },
  "chat_id": "chat_1769009405240_12c42x8",
  "version": "3",
  "name": "Offshore Viana do Castelo - Quick Inspection (XYZ)",
  "description": "Two-UAV quick inspection. 1 frontal waypoint per turbine at 162 m upwind (east) from hub, 80 m AGL, yaw -90° to face turbine, speed 5 m/s. Start/Return at HOME 20 m AGL. Nearest-neighbor ordering per UAV. All heights <=120 m; paths remain in front of rotor planes to avoid crossing rotor disks; >=5 m clearance from structures (>=130 m from blade tips).",
  "route": [
    {
      "name": "Line A - quick frontal",
      "uav": "px4_2",
      "id": 0,
      "attributes": {
        "max_vel": 6,
        "idle_vel": 3,
        "mode_yaw": 3,
        "mode_gimbal": 0,
        "mode_trace": 0,
        "mode_landing": 2
      },
      "wp": [
        {
          "pos": [
            1.52,
            -13.458,
            20
          ],
          "speed": 3
        },
        {
          "pos": [
            -578.998,
            -2.592,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -581.987,
            -96.393,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -580.492,
            -182.751,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -680.624,
            -181.262,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -680.624,
            -96.393,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -685.107,
            -4.08,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            1.52,
            -13.458,
            20
          ],
          "speed": 3
        }
      ],
      "uav_type": "px4_ros2"
    },
    {
      "name": "Line B - quick frontal",
      "uav": "px4_3",
      "id": 1,
      "attributes": {
        "max_vel": 6,
        "idle_vel": 3,
        "mode_yaw": 3,
        "mode_gimbal": 0,
        "mode_trace": 0,
        "mode_landing": 2
      },
      "wp": [
        {
          "pos": [
            -1.52,
            13.458,
            20
          ],
          "speed": 3
        },
        {
          "pos": [
            -583.481,
            86.742,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -686.602,
            88.231,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -807.656,
            88.231,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -807.656,
            -1.103,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -806.162,
            -85.971,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -806.162,
            -173.818,
            80
          ],
          "yaw": -90,
          "speed": 5,
          "gimbal": 0
        },
        {
          "pos": [
            -1.52,
            13.458,
            20
          ],
          "speed": 3
        }
      ],
      "uav_type": "px4_ros2"
    }
  ]
}
