// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EmptyResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EmptyResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEmptyResponse(bb:flatbuffers.ByteBuffer, obj?:EmptyResponse):EmptyResponse {
  return (obj || new EmptyResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEmptyResponse(bb:flatbuffers.ByteBuffer, obj?:EmptyResponse):EmptyResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EmptyResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startEmptyResponse(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endEmptyResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEmptyResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  EmptyResponse.startEmptyResponse(builder);
  return EmptyResponse.endEmptyResponse(builder);
}
}
