// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TriggerResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TriggerResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTriggerResponse(bb:flatbuffers.ByteBuffer, obj?:TriggerResponse):TriggerResponse {
  return (obj || new TriggerResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTriggerResponse(bb:flatbuffers.ByteBuffer, obj?:TriggerResponse):TriggerResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TriggerResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

success():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTriggerResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSuccess(builder:flatbuffers.Builder, success:boolean) {
  builder.addFieldInt8(0, +success, +false);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endTriggerResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTriggerResponse(builder:flatbuffers.Builder, success:boolean, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  TriggerResponse.startTriggerResponse(builder);
  TriggerResponse.addSuccess(builder, success);
  TriggerResponse.addMessage(builder, messageOffset);
  return TriggerResponse.endTriggerResponse(builder);
}
}
