// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TriggerRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TriggerRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTriggerRequest(bb:flatbuffers.ByteBuffer, obj?:TriggerRequest):TriggerRequest {
  return (obj || new TriggerRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTriggerRequest(bb:flatbuffers.ByteBuffer, obj?:TriggerRequest):TriggerRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TriggerRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startTriggerRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endTriggerRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTriggerRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  TriggerRequest.startTriggerRequest(builder);
  return TriggerRequest.endTriggerRequest(builder);
}
}
