// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';


export class Quaternion {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Quaternion {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQuaternion(bb:flatbuffers.ByteBuffer, obj?:Quaternion):Quaternion {
  return (obj || new Quaternion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQuaternion(bb:flatbuffers.ByteBuffer, obj?:Quaternion):Quaternion {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Quaternion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

z():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

w():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startQuaternion(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat64(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat64(2, y, 0.0);
}

static addZ(builder:flatbuffers.Builder, z:number) {
  builder.addFieldFloat64(3, z, 0.0);
}

static addW(builder:flatbuffers.Builder, w:number) {
  builder.addFieldFloat64(4, w, 0.0);
}

static endQuaternion(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQuaternion(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset, x:number, y:number, z:number, w:number):flatbuffers.Offset {
  Quaternion.startQuaternion(builder);
  Quaternion.add_Metadata(builder, _MetadataOffset);
  Quaternion.addX(builder, x);
  Quaternion.addY(builder, y);
  Quaternion.addZ(builder, z);
  Quaternion.addW(builder, w);
  return Quaternion.endQuaternion(builder);
}
}
