// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';
import { Twist } from '../../fb/geometry-msgs/twist.js';
import { Header } from '../../fb/std-msgs/header.js';


export class TwistStamped {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TwistStamped {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTwistStamped(bb:flatbuffers.ByteBuffer, obj?:TwistStamped):TwistStamped {
  return (obj || new TwistStamped()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTwistStamped(bb:flatbuffers.ByteBuffer, obj?:TwistStamped):TwistStamped {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TwistStamped()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

header(obj?:Header):Header|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Header()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

twist(obj?:Twist):Twist|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Twist()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startTwistStamped(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addHeader(builder:flatbuffers.Builder, headerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, headerOffset, 0);
}

static addTwist(builder:flatbuffers.Builder, twistOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, twistOffset, 0);
}

static endTwistStamped(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // header
  builder.requiredField(offset, 8) // twist
  return offset;
}

}
