// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';
import { ConfigMissionRequest } from '../../fb/aerialcore-common/config-mission-request.js';
import { ConfigMissionResponse } from '../../fb/aerialcore-common/config-mission-response.js';


export class ConfigMission {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConfigMission {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConfigMission(bb:flatbuffers.ByteBuffer, obj?:ConfigMission):ConfigMission {
  return (obj || new ConfigMission()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConfigMission(bb:flatbuffers.ByteBuffer, obj?:ConfigMission):ConfigMission {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConfigMission()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

request(obj?:ConfigMissionRequest):ConfigMissionRequest|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ConfigMissionRequest()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

response(obj?:ConfigMissionResponse):ConfigMissionResponse|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ConfigMissionResponse()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startConfigMission(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addRequest(builder:flatbuffers.Builder, requestOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, requestOffset, 0);
}

static addResponse(builder:flatbuffers.Builder, responseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, responseOffset, 0);
}

static endConfigMission(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
