// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';
import { eventRequest } from '../../fb/aerialcore-common/event-request.js';
import { eventResponse } from '../../fb/aerialcore-common/event-response.js';


export class eventService {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):eventService {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAseventService(bb:flatbuffers.ByteBuffer, obj?:eventService):eventService {
  return (obj || new eventService()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAseventService(bb:flatbuffers.ByteBuffer, obj?:eventService):eventService {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new eventService()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

request(obj?:eventRequest):eventRequest|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new eventRequest()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

response(obj?:eventResponse):eventResponse|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new eventResponse()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static starteventService(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addRequest(builder:flatbuffers.Builder, requestOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, requestOffset, 0);
}

static addResponse(builder:flatbuffers.Builder, responseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, responseOffset, 0);
}

static endeventService(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
