// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../fb/msg-metadata.js';


export class MsgWithMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MsgWithMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMsgWithMetadata(bb:flatbuffers.ByteBuffer, obj?:MsgWithMetadata):MsgWithMetadata {
  return (obj || new MsgWithMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMsgWithMetadata(bb:flatbuffers.ByteBuffer, obj?:MsgWithMetadata):MsgWithMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MsgWithMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMsgWithMetadata(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static endMsgWithMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMsgWithMetadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset):flatbuffers.Offset {
  MsgWithMetadata.startMsgWithMetadata(builder);
  MsgWithMetadata.add_Metadata(builder, _MetadataOffset);
  return MsgWithMetadata.endMsgWithMetadata(builder);
}
}
