// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';


export class Float32 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Float32 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFloat32(bb:flatbuffers.ByteBuffer, obj?:Float32):Float32 {
  return (obj || new Float32()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFloat32(bb:flatbuffers.ByteBuffer, obj?:Float32):Float32 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Float32()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

data():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startFloat32(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addData(builder:flatbuffers.Builder, data:number) {
  builder.addFieldFloat32(1, data, 0.0);
}

static endFloat32(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFloat32(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset, data:number):flatbuffers.Offset {
  Float32.startFloat32(builder);
  Float32.add_Metadata(builder, _MetadataOffset);
  Float32.addData(builder, data);
  return Float32.endFloat32(builder);
}
}
