// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';


export class UInt8 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UInt8 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUInt8(bb:flatbuffers.ByteBuffer, obj?:UInt8):UInt8 {
  return (obj || new UInt8()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUInt8(bb:flatbuffers.ByteBuffer, obj?:UInt8):UInt8 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UInt8()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

data():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startUInt8(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addData(builder:flatbuffers.Builder, data:number) {
  builder.addFieldInt8(1, data, 0);
}

static endUInt8(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUInt8(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset, data:number):flatbuffers.Offset {
  UInt8.startUInt8(builder);
  UInt8.add_Metadata(builder, _MetadataOffset);
  UInt8.addData(builder, data);
  return UInt8.endUInt8(builder);
}
}
