// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgMetadata } from '../../fb/msg-metadata.js';
import { PoseWithCovariance } from '../../fb/geometry-msgs/pose-with-covariance.js';
import { TwistWithCovariance } from '../../fb/geometry-msgs/twist-with-covariance.js';
import { Header } from '../../fb/std-msgs/header.js';


export class Odometry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Odometry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOdometry(bb:flatbuffers.ByteBuffer, obj?:Odometry):Odometry {
  return (obj || new Odometry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOdometry(bb:flatbuffers.ByteBuffer, obj?:Odometry):Odometry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Odometry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

_Metadata(obj?:MsgMetadata):MsgMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MsgMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

header(obj?:Header):Header|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Header()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

childFrameId():string|null
childFrameId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
childFrameId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pose(obj?:PoseWithCovariance):PoseWithCovariance|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PoseWithCovariance()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

twist(obj?:TwistWithCovariance):TwistWithCovariance|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new TwistWithCovariance()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startOdometry(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static add_Metadata(builder:flatbuffers.Builder, _MetadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, _MetadataOffset, 0);
}

static addHeader(builder:flatbuffers.Builder, headerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, headerOffset, 0);
}

static addChildFrameId(builder:flatbuffers.Builder, childFrameIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, childFrameIdOffset, 0);
}

static addPose(builder:flatbuffers.Builder, poseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, poseOffset, 0);
}

static addTwist(builder:flatbuffers.Builder, twistOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, twistOffset, 0);
}

static endOdometry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // header
  builder.requiredField(offset, 8) // child_frame_id
  builder.requiredField(offset, 10) // pose
  builder.requiredField(offset, 12) // twist
  return offset;
}

}
