// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EmptyRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EmptyRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEmptyRequest(bb:flatbuffers.ByteBuffer, obj?:EmptyRequest):EmptyRequest {
  return (obj || new EmptyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEmptyRequest(bb:flatbuffers.ByteBuffer, obj?:EmptyRequest):EmptyRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EmptyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startEmptyRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endEmptyRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEmptyRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  EmptyRequest.startEmptyRequest(builder);
  return EmptyRequest.endEmptyRequest(builder);
}
}
